<?php

/*
 * Configuración del módulo de correo: validación de entregabilidad,
 * listas de dominios descartables y caché de lookups MX.
 */
return [
    'mx_cache_ttl' => env('EMAIL_MX_CACHE_TTL', 3600),

    'dns_timeout_seconds' => env('EMAIL_DNS_TIMEOUT', 3),

    'disposable_domains' => array_values(array_filter(array_map('trim', explode(',', env('EMAIL_DISPOSABLE_DOMAINS', implode(',', [
        'mailinator.com',
        'guerrillamail.com',
        'guerrillamail.net',
        'guerrillamail.org',
        'guerrillamail.biz',
        'sharklasers.com',
        'yopmail.com',
        'yopmail.fr',
        'tempmail.com',
        'temp-mail.org',
        'temp-mail.io',
        'temp-mail.net',
        'tempmailo.com',
        'tempemail.com',
        'tempemail.net',
        '10minutemail.com',
        '10minutemail.net',
        'minutemail.com',
        'maildrop.cc',
        'mailnesia.com',
        'getnada.com',
        'discard.email',
        'discardmail.com',
        'fakeinbox.com',
        'fakemailgenerator.com',
        'trashmail.com',
        'trashmail.net',
        'trashmail.io',
        'throwawaymail.com',
        'throwaway.email',
        'mailcatch.com',
        'mailpoof.com',
        'mailtothu.com',
        'mail-temporaire.fr',
        'jetable.org',
        'moakt.com',
        'armyspy.com',
        'cuvox.de',
        'dayrep.com',
        'einrot.com',
        'fleckens.hu',
        'gustr.com',
        'jourrapide.com',
        'rhyta.com',
        'superrito.com',
        'teleworm.us',
    ])))))),
];
